print("************************************************")
print("*                                              *")
print("*                                              *")
print("*       bienvenidos a 6to de primaria          *")
print("************************************************")
print("*                                              *")
print("*                                              *")
print("*        🌞PROGRAMANDO EN PYTHON 🐍           *")
print("*                                              *")
print("*                                              *")
print("*                                              *")
print("*     🚀aprendemos a usar la pomputdora        *")
print("*     🚀creamos programas divertidos           *")
print("*     🚀resolvemos retos con actividades       *")
print("*                                              *")
print("************************************************")
print("*                                              *")
print("*  FRASE DEL DIA:                              *")
print("*  El conocimiento es poder                    *")
print("*                                              *")
print("************************************************")
print("************************************************")
print("*                                              *")